#!/usr/bin/env node
/**
 * Regenerate packages/monad/test/fixtures/canonical-abi.json from the compiled
 * XYXDeliveryProtocol artifact.
 *
 * Run `npm run build:contracts` first. This script never compiles Solidity
 * itself and never contacts a network, a faucet, or an explorer.
 *
 * The snapshot exists so `npm test` can verify SDK ABI parity on a checkout that
 * has not been built yet; `npm run test:abi:drift` is the backstop that proves
 * the snapshot still matches a fresh `forge build`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const ARTIFACT = path.join(
  REPO_ROOT,
  'packages',
  'contracts',
  'out',
  'XYXDeliveryProtocol.sol',
  'XYXDeliveryProtocol.json'
);
const SNAPSHOT = path.join(
  REPO_ROOT,
  'packages',
  'monad',
  'test',
  'fixtures',
  'canonical-abi.json'
);

const artifact = JSON.parse(readFileSync(ARTIFACT, 'utf8'));

writeFileSync(
  SNAPSHOT,
  `${JSON.stringify(
    {
      $schema: 'xyx-monad-canonical-abi-snapshot/v1',
      description:
        'Generated by `npm run sync:abi` from `forge build --root packages/contracts`. Do not edit by hand. packages/monad/test/abi-parity.test.ts compares deliveryProtocolAbi against this snapshot when the compiled artifact is absent, and `npm run test:abi:drift` fails if this snapshot disagrees with a fresh build.',
      XYXDeliveryProtocol: { abi: artifact.abi },
    },
    null,
    2
  )}\n`
);

console.log(`Wrote ${path.relative(REPO_ROOT, SNAPSHOT)} (${artifact.abi.length} ABI entries)`);
