#!/usr/bin/env node
/**
 * Prove the committed ABI snapshot matches a fresh `forge build`.
 *
 * `npm test` can fall back to the snapshot when packages/contracts/out/ is
 * absent, which would let a stale snapshot silently become the SDK's source of
 * truth. This script rebuilds nothing itself — it reads the artifact
 * `npm run build:contracts` produced and fails if the snapshot differs by even
 * one field, so the fallback can never rot.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const ARTIFACT = path.join(
  REPO_ROOT,
  'packages',
  'contracts',
  'out',
  'XYXDeliveryProtocol.sol',
  'XYXDeliveryProtocol.json'
);
const SNAPSHOT = path.join(
  REPO_ROOT,
  'packages',
  'monad',
  'test',
  'fixtures',
  'canonical-abi.json'
);

function canonical(value: unknown): string {
  return JSON.stringify(value, (_k, v) => (typeof v === 'bigint' ? v.toString() : v), 2);
}

const artifact = JSON.parse(readFileSync(ARTIFACT, 'utf8'));
const snapshot = JSON.parse(readFileSync(SNAPSHOT, 'utf8'));

const fresh = {
  $schema: 'xyx-monad-canonical-abi-snapshot/v1',
  description:
    'Generated by `npm run sync:abi` from `forge build --root packages/contracts`. Do not edit by hand. packages/monad/test/abi-parity.test.ts compares deliveryProtocolAbi against this snapshot when the compiled artifact is absent, and `npm run test:abi:drift` fails if this snapshot disagrees with a fresh build.',
  XYXDeliveryProtocol: { abi: artifact.abi },
};

if (canonical(fresh) !== canonical(snapshot)) {
  // Show exactly what drifted instead of a bare "mismatch".
  const dir = mkdtempSync(path.join(tmpdir(), 'xyx-abi-drift-'));
  writeFileSync(path.join(dir, 'fresh.json'), `${canonical(fresh)}\n`);
  writeFileSync(path.join(dir, 'committed.json'), `${canonical(snapshot)}\n`);
  try {
    mkdirSync(dir, { recursive: true });
    execFileSync('diff', ['-u', path.join(dir, 'committed.json'), path.join(dir, 'fresh.json')], {
      stdio: 'inherit',
    });
  } catch {
    // diff exits 1 on differences; its output already printed above.
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
  console.error(
    `ABI_DRIFT: ${path.relative(REPO_ROOT, SNAPSHOT)} no longer matches the compiled artifact.` +
      ' Run `npm run sync:abi` and commit the result.'
  );
  process.exit(1);
}

console.log(
  `ABI snapshot is in sync with the compiled artifact (${artifact.abi.length} ABI entries).`
);
