/**
 * ABI parity: the hand-maintained SDK ABI must match the COMPILED contract.
 *
 * The SDK ships `deliveryProtocolAbi` as a literal so consumers never need a
 * build step to import it. That convenience is exactly how drift happens: a
 * literal is well-typed no matter how wrong it is, so `tsc --noEmit` cannot
 * catch a wrong field order and no behavioural test notices as long as nobody
 * asserts a selector. This suite closes that hole by comparing the literal
 * against `forge build`'s own artifact and by asserting the encoded selector.
 *
 * Source of truth: packages/contracts/out/XYXDeliveryProtocol.sol/*.json,
 * produced by `npm run build:contracts`. Because `npm test` may be run before
 * that on a clean checkout, an equivalent snapshot generated by
 * `npm run sync:abi` is committed alongside these tests and used as a
 * documented fallback. The snapshot cannot rot unnoticed: `npm run test:abi:drift`
 * regenerates the artifact and fails if the snapshot differs from it.
 */

import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';

import {
  decodeEventLog,
  encodeAbiParameters,
  encodeFunctionData,
  padHex,
  parseAbiItem,
  toEventSelector,
  toFunctionSelector,
  toHex,
} from 'viem';

import { deliveryProtocolAbi, passkeyRegistryAbi } from '../src/protocol';

const TEST_DIR = path.dirname(fileURLToPath(import.meta.url));
// packages/monad/test -> packages/monad -> packages -> repo root
const REPO_ROOT = path.resolve(TEST_DIR, '..', '..', '..');

const PROTOCOL_ARTIFACT = path.join(
  REPO_ROOT,
  'packages',
  'contracts',
  'out',
  'XYXDeliveryProtocol.sol',
  'XYXDeliveryProtocol.json'
);
const REGISTRY_ARTIFACT = path.join(REPO_ROOT, 'packages', 'contracts', 'out', 'XYXPasskeyRegistry.sol', 'XYXPasskeyRegistry.json');
const ABI_SNAPSHOT = path.join(TEST_DIR, 'fixtures', 'canonical-abi.json');

/** The canonical `resolveJob` selector, derived from the compiled signature. */
const RESOLVE_JOB_SELECTOR = '0xe1efa0a1';
const RESOLVE_JOB_SIGNATURE =
  'resolveJob((uint256,bytes32,bytes32,bytes32,bytes32,uint8,uint64,uint64,uint64),(bytes32,bytes32,uint256,uint256,bytes,string))';

function loadCompiledProtocolAbi(): { abi: AbiEntry[]; source: string } {
  if (existsSync(PROTOCOL_ARTIFACT)) {
    const artifact = JSON.parse(readFileSync(PROTOCOL_ARTIFACT, 'utf8')) as {
      abi: AbiEntry[];
    };
    return { abi: artifact.abi, source: 'compiled Foundry artifact' };
  }
  if (existsSync(ABI_SNAPSHOT)) {
    const snapshot = JSON.parse(readFileSync(ABI_SNAPSHOT, 'utf8')) as {
      XYXDeliveryProtocol: { abi: AbiEntry[] };
    };
    return { abi: snapshot.XYXDeliveryProtocol.abi, source: 'committed ABI snapshot' };
  }
  throw new Error(
    'ABI_PARITY_PREREQUISITE_MISSING: neither packages/contracts/out/XYXDeliveryProtocol.sol/' +
      'XYXDeliveryProtocol.json nor packages/monad/test/fixtures/canonical-abi.json exists. ' +
      'Run `npm run build:contracts` (or `npm run sync:abi`) before `npm test`.'
  );
}

interface AbiParam {
  name?: string;
  type: string;
  internalType?: string;
  indexed?: boolean;
  components?: AbiParam[];
}

interface AbiEntry {
  type: string;
  name?: string;
  inputs?: AbiParam[];
  outputs?: AbiParam[];
  stateMutability?: string;
  anonymous?: boolean;
}

function findEntry(abi: AbiEntry[], type: string, name: string): AbiEntry {
  const match = abi.find((e) => e.type === type && e.name === name);
  if (!match) throw new Error(`ABI entry not found: ${type} ${name}`);
  return match;
}

/** Exact canonical signature string, as used for selector derivation. */
function signatureOf(entry: AbiEntry): string {
  const inner = (entry.inputs ?? [])
    .map((i) =>
      i.type === 'tuple'
        ? `(${(i.components ?? []).map((c) => c.type).join(',')})`
        : i.type
    )
    .join(',');
  return `${entry.name}(${inner})`;
}

/** Structural projection of an entry's inputs, for element-wise comparison. */
function inputShape(entry: AbiEntry) {
  return (entry.inputs ?? []).map((i) => ({
    name: i.name,
    type: i.type,
    internalType: i.internalType,
    components: (i.components ?? []).map((c) => ({
      name: c.name,
      type: c.type,
      internalType: c.internalType,
    })),
  }));
}

const WEBAUTHN_AUTH_ORDER: Array<[string, string]> = [
  ['r', 'bytes32'],
  ['s', 'bytes32'],
  ['challengeIndex', 'uint256'],
  ['typeIndex', 'uint256'],
  ['authenticatorData', 'bytes'],
  ['clientDataJSON', 'string'],
];

describe('deliveryProtocolAbi parity with the compiled contract', () => {
  const { abi: compiledAbi, source } = loadCompiledProtocolAbi();
  const sdkAbi = deliveryProtocolAbi as unknown as AbiEntry[];

  it(`loads the compiled ABI from the ${source}`, () => {
    assert.ok(compiledAbi.length > 0, 'compiled ABI is empty');
  });

  it('declares resolveJob with the exact canonical signature and selector', () => {
    const sdk = findEntry(sdkAbi, 'function', 'resolveJob');
    assert.equal(signatureOf(sdk), RESOLVE_JOB_SIGNATURE);
    assert.equal(toFunctionSelector(signatureOf(sdk)), RESOLVE_JOB_SELECTOR);
    // The compiled artifact must select the same function, so a Solidity
    // signature change on either side is caught here.
    assert.equal(signatureOf(findEntry(compiledAbi, 'function', 'resolveJob')), signatureOf(sdk));
  });

  it('encodes resolveJob calldata whose 4-byte selector is the canonical one', () => {
    const verdict = {
      jobId: 1n,
      termsCommitment: `0x${'11'.repeat(32)}`,
      deliveryCommitment: `0x${'22'.repeat(32)}`,
      evidenceCommitment: `0x${'33'.repeat(32)}`,
      reasonCommitment: `0x${'44'.repeat(32)}`,
      decision: 1,
      issuedAt: 1_700_000_000n,
      expiresAt: 1_700_003_600n,
      nonce: 7n,
    };
    const assertion = {
      r: `0x${'aa'.repeat(32)}`,
      s: `0x${'bb'.repeat(32)}`,
      challengeIndex: 33n,
      typeIndex: 55n,
      authenticatorData: '0xa1',
      clientDataJSON: '{"type":"webauthn.get","challenge":"AAAA"}',
    };

    const data = encodeFunctionData({
      abi: deliveryProtocolAbi as never,
      functionName: 'resolveJob',
      args: [verdict, assertion],
    });
    assert.equal(data.slice(0, 10), RESOLVE_JOB_SELECTOR);
  });

  it('declares WebAuthn.WebAuthnAuth with six fields in OpenZeppelin order', () => {
    const tuple = (findEntry(sdkAbi, 'function', 'resolveJob').inputs ?? []).find(
      (i) => i.name === 'assertion'
    );
    assert.ok(tuple, 'resolveJob must declare an `assertion` tuple');
    const comps = tuple.components ?? [];
    assert.equal(comps.length, 6, 'WebAuthnAuth must have exactly six fields');
    assert.deepEqual(
      comps.map((c) => [c.name, c.type]),
      WEBAUTHN_AUTH_ORDER
    );
  });

  it('mirrors the compiled resolveJob entry element for element', () => {
    assert.deepEqual(
      inputShape(findEntry(sdkAbi, 'function', 'resolveJob')),
      inputShape(findEntry(compiledAbi, 'function', 'resolveJob'))
    );
  });

  it('declares PaymentReleased with recipient indexed, as the contract emits it', () => {
    const sdk = findEntry(sdkAbi, 'event', 'PaymentReleased');
    const compiled = findEntry(compiledAbi, 'event', 'PaymentReleased');
    assert.deepEqual(
      (sdk.inputs ?? []).map((i) => [i.name, i.type, i.indexed]),
      (compiled.inputs ?? []).map((i) => [i.name, i.type, i.indexed])
    );
    assert.equal((sdk.inputs ?? []).find((i) => i.name === 'recipient')?.indexed, true);
  });

  it('decodes PaymentReleased with recipient recovered from an indexed topic', () => {
    const recipient = '0x00000000000000000000000000000000000AbCdE';
    const jobId = 42n;
    const budget = 1_000_000n;

    // Build the log the way the contract emits it: jobId and recipient are indexed
    // (each a padded topic), budget is a packed data word.
    const signature =
      'PaymentReleased(uint256 indexed jobId, address indexed recipient, uint256 budget)';
    const topic0 = toEventSelector(signature);
    const topics = [topic0, padHex(toHex(jobId)), padHex(recipient.toLowerCase())] as [
      `0x${string}`,
      ...`0x${string}`[],
    ];
    const data = encodeAbiParameters([{ type: 'uint256' }], [budget]);

    // The log carries TWO indexed topics plus topic0, so viem reads the recipient
    // out of topics[2]. An SDK ABI that declared `recipient` unindexed would
    // decode a wrong address here instead of `recipient`.
    assert.equal(topics.length, 3);

    const decoded = decodeEventLog({
      abi: deliveryProtocolAbi as never,
      data,
      topics,
    });
    assert.equal(decoded.eventName, 'PaymentReleased');
    const args = decoded.args as { jobId: bigint; recipient: string; budget: bigint };
    assert.equal(args.jobId, jobId);
    assert.equal(args.recipient.toLowerCase(), recipient.toLowerCase());
    assert.equal(args.budget, budget);

    // Independent cross-check that the indexing is not an SDK-local invention.
    const item = parseAbiItem(
      'event PaymentReleased(uint256 indexed jobId, address indexed recipient, uint256 budget)'
    ) as { inputs: Array<{ indexed?: boolean }> };
    // viem omits `indexed` on non-indexed inputs, so normalize to booleans.
    assert.deepEqual(
      item.inputs.map((i) => i.indexed === true),
      [true, true, false]
    );
    assert.equal(toEventSelector('PaymentReleased(uint256 indexed jobId, address indexed recipient, uint256 budget)'), topic0);
  });

  it('exposes the canonical public getters used by SDK read helpers', () => {
    for (const name of ['consumedVerdicts', 'usedNonces', 'VERDICT_TYPEHASH', 'eip712Domain']) {
      const sdk = findEntry(sdkAbi, 'function', name);
      const compiled = findEntry(compiledAbi, 'function', name);
      assert.equal(sdk.stateMutability, 'view', `${name} must be view`);
      assert.equal(signatureOf(sdk), signatureOf(compiled));
    }
  });

  it('exposes the canonical JobCancelled event', () => {
    assert.deepEqual(
      (findEntry(sdkAbi, 'event', 'JobCancelled').inputs ?? []).map((i) => [
        i.name,
        i.type,
        i.indexed,
      ]),
      (findEntry(compiledAbi, 'event', 'JobCancelled').inputs ?? []).map((i) => [
        i.name,
        i.type,
        i.indexed,
      ])
    );
  });

  it('does not invent contract methods, roles, or pause controls', () => {
    const sdkNames = new Set(
      sdkAbi.filter((e) => e.type === 'function').map((e) => e.name as string)
    );
    const compiledNames = new Set(
      compiledAbi.filter((e) => e.type === 'function').map((e) => e.name as string)
    );

    const forbidden = [
      'pause',
      'unpause',
      'paused',
      'addAdmin',
      'removeAdmin',
      'grantRole',
      'revokeRole',
      'setAdmin',
      'hasRole',
      'owner',
      'transferOwnership',
      'complete',
      'reject',
      'completeJob',
      'rejectJob',
      'evaluate',
    ];
    for (const name of forbidden) {
      assert.ok(!sdkNames.has(name), `SDK ABI must not declare ${name}()`);
    }
    // And nothing the SDK declares may be absent from the real contract.
    for (const name of sdkNames) {
      assert.ok(compiledNames.has(name), `SDK ABI declares ${name}, absent from the contract`);
    }
  });

  it('keeps every passkeyRegistryAbi member named and non-empty', () => {
    for (const entry of passkeyRegistryAbi as unknown as AbiEntry[]) {
      assert.ok(entry.name, `passkeyRegistryAbi entry has no name: ${entry.type}`);
    }
  });
});

describe('passkeyRegistryAbi parity with the compiled contract', () => {
  it('encodes the real six-field WebAuthn registration call', () => {
    if (!existsSync(REGISTRY_ARTIFACT)) throw new Error('REGISTRY_ARTIFACT_MISSING: run npm run build:contracts');
    const artifact = JSON.parse(readFileSync(REGISTRY_ARTIFACT, 'utf8')) as { abi: AbiEntry[] };
    const sdk = passkeyRegistryAbi as unknown as AbiEntry[];
    for (const name of ['registrationChallenge', 'registerCredential', 'credentialOf', 'assertionChallenge', 'rpIdHash', 'p256Verifier']) {
      assert.equal(signatureOf(findEntry(sdk, 'function', name)), signatureOf(findEntry(artifact.abi, 'function', name)), `${name} signature drift`);
    }
    const registered = findEntry(sdk, 'function', 'registerCredential');
    const assertion = registered.inputs?.find(input => input.name === 'assertion');
    assert.deepEqual(assertion?.components?.map(component => [component.name, component.type]), WEBAUTHN_AUTH_ORDER);
    const calldata = encodeFunctionData({
      abi: passkeyRegistryAbi,
      functionName: 'registerCredential',
      args: [
        `0x${'11'.repeat(32)}`, `0x${'22'.repeat(32)}`, `0x${'33'.repeat(32)}`,
        { r: `0x${'44'.repeat(32)}`, s: `0x${'55'.repeat(32)}`, challengeIndex: 12n,
          typeIndex: 0n, authenticatorData: '0x0102', clientDataJSON: '{"type":"webauthn.get"}' },
      ],
    });
    assert.equal(calldata.slice(0, 10), toFunctionSelector(signatureOf(findEntry(artifact.abi, 'function', 'registerCredential'))));
  });
});
